language: ruby
env:
  - DEPLOY_TARGET_ENV=production
before_install:
  - echo "before install step"
install:
  - echo "install step"
before_script:
  - echo "beforre_script step"
script:
  - echo "script step"
before_cache:
  - echo "before_cache step"
after_success:
  - echo "after_success step"
after_failure:
  - echo "after_failure step"
before_deploy:
  - echo "before_deploy step"
deploy:
  - provider: script
    script: "echo deploy step: provider1 failed && false"
    on:
      all_branches: true
      condition: $DEPLOY_TARGET_ENV != ''
  - provider: script
    script: "echo deploy setp: provider1 faild but dispatch provider2"
    on:
      all_branches: true
      condition: $DEPLOY_TARGET_ENV != ''
after_deploy:
  - echo "after_deploy step"
after_script:
  - echo "after_script step"
